### ISSUE TITLE
Ada error saat enkripsi dan dekripsi file

### ISSUE THREAD

**Issue by vickzkater** [ryfan/Enkrip-Dekrip-AES#1]
Bila menjalankan program dari sourcecode yang dibagikan di Github ini ditemukan ada bug sederhana yang membuat aplikasi ini tidak dapat berjalan dengan semestinya.

Bug akan muncul saat melakukan proses enkripsi atau dekripsi file.
![image](https://user-images.githubusercontent.com/7297975/34903997-2f759236-f86f-11e7-96b8-10daaa9a903b.png)

**Comment by vickzkater** [comment]
Solusi fixing bug ini sederhana aja yaitu membuat folder dengan nama "file_encrypt" dan satu folder lagi dengan nama "file_decrypt" di dalam folder "dashboard".

Semoga membantu :)

**Comment by ryfan** [comment]
Terima kasih mas sudah diingatkan. folder "file_encrypt" dan folder "file_decrypt" tidak terpush dikarenakan folder tersebut kosong pada saat mau dipush. jadi musti dibuat manual untuk folder tersebut di dalam folder "dashboard" :)
