### ISSUE TITLE
database

### ISSUE THREAD

**Issue by anthero95** [ryfan/Enkrip-Dekrip-AES#2]
maaf kak saya dapat masalah pas mau masukin databse nya seallu error
2 errors were found during analysis.

Variable name was expected. (near " " at position 5)
Unrecognized statement type. (near "Host" at position 0)
SQL query:

Host: localhost (Version 5.5.5-10.1.21-MariaDB) # Date: 2017-07-14 16:09:20 # Generator: MySQL-Front 6.0 (Build 1.194) # # Structure for table "file" # DROP TABLE IF EXISTS `file`

MySQL said: Documentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Host: localhost  (Version 5.5.5-10.1.21-MariaDB)
# Date: 2017-07-14 16:09:20
#' at line 1

Mohon pencerahan

**Comment by ryfan** [comment]
Hi, coba menggunakan database ini ya
https://github.com/ryfan/Enkrip-Dekrip-AES/blob/master/db_kkp.sql
