### ISSUE TITLE
Error saat setelah melakukan login

### ISSUE THREAD

**Issue by davidsuji** [ryfan/Enkrip-Dekrip-AES#3]
mau tanya mas bro,, ini ada error seperti berikut :
Fatal error: Uncaught Error: Call to undefined function mysql_connect() in C:\xampp\htdocs\Enkrip-Dekrip-AES-master\config.php:6 Stack trace: #0 C:\xampp\htdocs\Enkrip-Dekrip-AES-master\auth.php(3): include() #1 {main} thrown in C:\xampp\htdocs\Enkrip-Dekrip-AES-master\config.php on line 6

itu errornya kenapa? dan versi XAMPP yang mas bro pakai versi yang berapa ya?

**Comment by ryfan** [comment]
halo mas david, versi phpnya hanya bisa di 5.6 kebawah. diaktifkan ekstensi php imap dan openssl.
